import { useMemo } from 'react';
import {
  ScrollView,
  StyleSheet,
  Text,
  View,
  Pressable,
} from 'react-native';
import { useRouter } from 'expo-router';

import { useTheme } from '@/providers/ThemeProvider';

type Section = {
  title: string;
  body: string[];
};

const UPDATED_AT = 'February 12, 2025';

const SECTIONS: Section[] = [
  {
    title: '1. Overview',
    body: [
      'BoothBrain (“we”, “our”, or “us”) provides software tools that help makers and market vendors manage inventory, sessions, and sales. By using the BoothBrain mobile or web experience (collectively, the “Service”), you agree to these Terms & Conditions.',
    ],
  },
  {
    title: '2. Eligibility & Accounts',
    body: [
      'You must be at least 18 years old and capable of entering into a binding agreement to create an account.',
      'You are responsible for maintaining the confidentiality of your credentials and for all activity conducted through your account.',
    ],
  },
  {
    title: '3. Acceptable Use',
    body: [
      'Do not upload unlawful, misleading, or infringing content.',
      'Do not interfere with the Service, attempt unauthorized access, or use automated means to scrape data.',
      'You are solely responsible for compliance with local tax, licensing, and regulatory obligations that apply to your business.',
    ],
  },
  {
    title: '4. Plans & Limits',
    body: [
      'Free plan accounts may store up to 5 active items total, inclusive of staged inventory. Additional capacity requires an upgraded plan.',
      'We may modify plan pricing, limits, or features with reasonable notice. Continued use after changes constitutes acceptance.',
    ],
  },
  {
    title: '5. Billing & Renewals',
    body: [
      'Paid subscriptions renew automatically unless cancelled at least one day before the renewal date.',
      'Fees are non‑refundable except where required by law. You remain responsible for charges incurred prior to cancellation.',
    ],
  },
  {
    title: '6. Data & Privacy',
    body: [
      'We store account, inventory, and usage data to provide the Service. We do not sell personal data to third parties.',
      'You can request deletion of your account by contacting hello@boothbrain.com. Some data may be retained to meet legal obligations.',
      'For additional details, refer to the Privacy section below.',
    ],
  },
  {
    title: '7. Content Ownership',
    body: [
      'You retain ownership of the content you upload. By submitting content, you grant us a non-exclusive, worldwide license to host, display, and use it solely to operate the Service.',
      'We may remove content that violates these Terms.',
    ],
  },
  {
    title: '8. Third-Party Services',
    body: [
      'The Service may integrate with third-party payment processors or analytics tools. Those services are governed by their own agreements and privacy practices.',
    ],
  },
  {
    title: '9. Termination',
    body: [
      'You may cancel your account at any time within the app or by contacting support.',
      'We may suspend or terminate access if you violate these Terms or misuse the Service. We are not liable for losses arising from termination.',
    ],
  },
  {
    title: '10. Disclaimers',
    body: [
      'The Service is provided “as is” without warranties of any kind. We do not guarantee uninterrupted availability or accuracy of data.',
      'You assume all risk for reliance on reports, analytics, or calculations produced by the Service.',
    ],
  },
  {
    title: '11. Limitation of Liability',
    body: [
      'To the fullest extent permitted by law, our aggregate liability for claims arising out of or related to the Service will not exceed the amount you paid to use the Service in the six (6) months preceding the claim.',
    ],
  },
  {
    title: '12. Changes to These Terms',
    body: [
      'We may update these Terms from time to time. Material changes will be posted in-app or communicated by email. Continued use after notice constitutes acceptance of the updated Terms.',
    ],
  },
  {
    title: '13. Privacy Summary',
    body: [
      'We collect information you provide (such as profile details, items, staged inventory) and usage data generated by your interactions with the Service.',
      'Data is used to deliver features, maintain security, improve the Service, and communicate updates. We may share limited data with trusted processors that help us operate BoothBrain.',
      'You can export or delete personal data by contacting hello@boothbrain.com. We will respond within a reasonable timeframe.',
    ],
  },
  {
    title: '14. Contact',
    body: [
      'Questions about these Terms or requests related to your account can be sent to hello@boothbrain.com.',
    ],
  },
];

export default function TermsScreen() {
  const router = useRouter();
  const { theme } = useTheme();

  const renderedSections = useMemo(
    () =>
      SECTIONS.map((section) => (
        <View key={section.title} style={styles.section}>
          <Text style={[styles.sectionTitle, { color: theme.colors.textPrimary }]}>{section.title}</Text>
          {section.body.map((paragraph) => (
            <Text key={paragraph} style={[styles.sectionBody, { color: theme.colors.textSecondary }]}>
              {paragraph}
            </Text>
          ))}
        </View>
      )),
    [theme.colors.textPrimary, theme.colors.textSecondary],
  );

  return (
    <View style={[styles.container, { backgroundColor: theme.colors.background }]}>
      <View style={[styles.header, { borderColor: theme.colors.border }]}>
        <Text style={[styles.title, { color: theme.colors.textPrimary }]}>Terms & Privacy</Text>
        <Text style={[styles.subtitle, { color: theme.colors.textSecondary }]}>Updated {UPDATED_AT}</Text>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {renderedSections}
      </ScrollView>

        <Pressable
          style={[styles.closeButton, { backgroundColor: theme.colors.primary }]}
          onPress={() => router.back()}
        >
          <Text style={[styles.closeButtonText, { color: theme.colors.surface }]}>Back</Text>
        </Pressable>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
  },
  subtitle: {
    marginTop: 4,
    fontSize: 13,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    gap: 20,
  },
  section: {
    gap: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
  },
  sectionBody: {
    fontSize: 14,
    lineHeight: 20,
  },
  closeButton: {
    margin: 20,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
});
